# Generated by Django 3.1.4 on 2020-12-21 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacttubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttubers',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contacttubers',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
