# Generated by Django 3.1.4 on 2020-12-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201211_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('camera', 'camera'), ('nikon', 'nikon'), ('sony', 'sony'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('technical', 'technical'), ('cooking', 'cooking')], max_length=255),
        ),
    ]
