# Generated by Django 3.1.4 on 2020-12-17 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiretubers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('tubers_id', models.IntegerField(blank=True)),
                ('tuber_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('message', models.TextField(blank=True)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
